---
title: "2022 Table Test"
author: "Randi Bolt"
date: "5/12/2022"
output: html_document
---

```{r, include=FALSE}
here::i_am("sandbox/2022_table_test.Rmd")

library(reactable)
library(magrittr)
library(dplyr)
```


```{r load data, include=FALSE, echo=FALSE}
# variables
date_today <- readRDS(here::here("clean_data",
                                  "date_today.rds"))
date_data <- readRDS(here::here("clean_data",
                                "date_data.rds"))
# data
us_clean <- readRDS(here::here("clean_data",
                               "us_covid_clean.rds"))
or_clean <- readRDS(here::here("clean_data",
                               "or_covid_clean.rds"))
us_current <- readRDS(here::here("clean_data",
                               paste0("us_", date_data, ".rds")))
or_current <- readRDS(here::here("clean_data",
                               paste0("or_", date_data, ".rds")))
```

```{r}
# create new df without Date column
us_tb_01 <-us_current %>% select(!Date)
# Add commas to: 
# us_tb_01$Population <-base::prettyNum(us_tb_01$Population, big.mark = ",")
# us_tb_01$Cases <-base::prettyNum(us_tb_01$Cases, big.mark = ",")
# us_tb_01$Deaths <-base::prettyNum(us_tb_01$Deaths, big.mark = ",")
# us_tb_01$full_vacc <-base::prettyNum(us_tb_01$full_vacc, big.mark = ",")
# us_tb_01$partial_vacc <-base::prettyNum(us_tb_01$partial_vacc, big.mark = ",")
# # add % to 
# us_tb_01$cases_per_pop <- base::sprintf("%0.2f%%", us_tb_01$cases_per_pop*100)
# us_tb_01$deaths_per_pop <- base::sprintf("%0.2f%%", us_tb_01$deaths_per_pop*100)

head(us_tb_01)
```

```{r}
reactable(us_current %>% 
            # remove date column
            dplyr::select(!Date),
          # modify columns 
          columns = list(Population = colDef(format = colFormat(separators = TRUE)),
                         Cases = colDef(format = colFormat(separators = TRUE)),
                         cases_per_pop = colDef(name = "Percent of Cases", 
                                                format = colFormat(percent = TRUE,
                                                                   digits = 2)),
                         Deaths = colDef(format = colFormat(separators = TRUE)),
                         deaths_per_pop = colDef(name = "Percent of Deaths",
                                                 format = colFormat(percent = TRUE,
                                                                    digits = 2)),
                         full_vacc = colDef(name = "Fully Vaccinated",
                                            format = colFormat(separators = TRUE)),
                         full_vacc_per_pop = colDef(name = "Percent Fully Vaccinated",
                                                    format = colFormat(percent = TRUE,
                                                                       digits = 2)),
                         partial_vacc = colDef(name = "Partially Vaccinated",
                                               format = colFormat(separators = TRUE)),
                         partial_vacc_per_pop = colDef(name = "Percent Partially Vaccinated",
                                                       format = colFormat(percent = TRUE, digits = 2))),
                     defaultSorted = list(Cases = "desc"),
                     bordered = TRUE,
                     highlight = TRUE,
                     showPageSizeOptions = TRUE,
                     pageSizeOptions = c(5, 10, 20, 50),
                     defaultPageSize = 5)
```


```{r}
library(reactable)
options(reactable.theme = reactableTheme(
  color = "hsl(233, 9%, 87%)",
  backgroundColor = "hsl(233, 9%, 19%)",
  borderColor = "hsl(233, 9%, 22%)",
  stripedColor = "hsl(233, 12%, 22%)",
  highlightColor = "hsl(233, 12%, 24%)",
  inputStyle = list(backgroundColor = "hsl(233, 9%, 25%)"),
  selectStyle = list(backgroundColor = "hsl(233, 9%, 25%)"),
  pageButtonHoverStyle = list(backgroundColor = "hsl(233, 9%, 25%)"),
  pageButtonActiveStyle = list(backgroundColor = "hsl(233, 9%, 28%)")
))
reactable(us_tb_01,
           defaultSorted = "State",
                     bordered = TRUE,
                     highlight = TRUE,
                     showPageSizeOptions = TRUE,
                     pageSizeOptions = c(5, 10, 20, 50),
                     defaultPageSize = 5)
```



```{r}
# new cases oregon
or_new_cases <- us_clean %>%
  select(Date, State, Cases) %>%
  filter(State == "Oregon") %>%
  arrange(Date) %>%
  mutate(New_Cases = Cases - lag(Cases, default = first(Cases)))
barplot(or_new_cases$New_Cases)
```
