---
title: "2022_prophet"
author: "Randi Bolt"
date: "5/14/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
here::i_am("sandbox/2022_table_test.Rmd")
```

```{r}
library(reactable)
library(magrittr)
library(dplyr)
library(prophet)
```

```{r load data, include=FALSE, echo=FALSE}
# variables
date_today <- readRDS(here::here("clean_data",
                                  "date_today.rds"))
date_data <- readRDS(here::here("clean_data",
                                "date_data.rds"))
# data
us_clean <- readRDS(here::here("clean_data",
                               "us_covid_clean.rds"))
or_clean <- readRDS(here::here("clean_data",
                               "or_covid_clean.rds"))
us_current <- readRDS(here::here("clean_data",
                               paste0("us_", date_data, ".rds")))
or_current <- readRDS(here::here("clean_data",
                               paste0("or_", date_data, ".rds")))
```

```{r}
# oregon
us_or <- us_clean %>%
  filter(State == "Oregon") %>%
  summarise(ds = Date,
            y = Cases)
head(us_or)
# call prophet function to fit the model 
Model1 <- prophet(us_or, daily.seasonality=TRUE)
Future1 <- make_future_dataframe(Model1, periods = 365*3)
tail(Future1)
# Forecast Proper 
Forecast1 <- predict(Model1, Future1)
# Forecast Values 
predict_date <- Forecast1$ds[length(Forecast1$ds)]
predict_value <- Forecast1$yhat[length(Forecast1$yhat)]
predict_lower <- Forecast1$yhat_lower[length(Forecast1$yhat_lower)]
predict_upper <- Forecast1$yhat_upper[length(Forecast1$yhat_upper)]
# plot model
dyplot.prophet(Model1, Forecast1)
# plot componets
prophet_plot_components(Model1, Forecast1)
```

```{r}
# multnomah county
or_mult <- or_clean %>%
  filter(County == "Multnomah") %>%
  summarise(ds = Date,
            y = Cases)
head(or_mult)
# call prophet function to fit the model 
Model1 <- prophet(or_mult, daily.seasonality=TRUE)
Future1 <- make_future_dataframe(Model1, periods = 365*3)
tail(Future1)
# Forecast Proper 
Forecast1 <- predict(Model1, Future1)
# Forecast Values 
predict_date <- Forecast1$ds[length(Forecast1$ds)]
predict_value <- Forecast1$yhat[length(Forecast1$yhat)]
predict_lower <- Forecast1$yhat_lower[length(Forecast1$yhat_lower)]
predict_upper <- Forecast1$yhat_upper[length(Forecast1$yhat_upper)]
# plot model
dyplot.prophet(Model1, Forecast1)
# plot componets
prophet_plot_components(Model1, Forecast1)
```

