---
title: "Figures"
knit: (function(input_file, encoding) {
  out_dir <- '../docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'figs.html'))})
output:
  html_document:
    toc: true
    toc_float: true
    theme: darkly
---

```{r, include=FALSE}
here::i_am("04_website/figs.Rmd")
```

```{r load data, include=FALSE}
# library
library(reactable)
library(magrittr)
library(dplyr)
library(gt)
# location of data
location_of_dates_data <- here::here("01_data/clean_data",
                                     "clean_data_dates.rds")
location_of_current <- here::here("01_data/clean_data",
                                  "clean_data_current.rds")

# save data
date_today <- base::readRDS(location_of_dates_data)[[1]]
us_data_date <- base::readRDS(location_of_dates_data)[[4]]
or_data_date <- base::readRDS(location_of_dates_data)[[5]]
us_current <- base::readRDS(location_of_current)[[1]]
or_current <- base::readRDS(location_of_current)[[2]]

# nightmode theme for reactables
options(reactable.theme = reactableTheme(
  color = "hsl(233, 9%, 87%)",
  backgroundColor = "hsl(233, 9%, 19%)",
  borderColor = "hsl(233, 9%, 22%)",
  stripedColor = "hsl(233, 12%, 22%)",
  highlightColor = "hsl(233, 12%, 24%)",
  inputStyle = list(backgroundColor = "hsl(233, 9%, 25%)"),
  selectStyle = list(backgroundColor = "hsl(233, 9%, 25%)"),
  pageButtonHoverStyle = list(backgroundColor = "hsl(233, 9%, 25%)"),
  pageButtonActiveStyle = list(backgroundColor = "hsl(233, 9%, 28%)")
))
```


# US FIGS.

## Tables 

```{r, echo=FALSE}
reactable::reactable(us_current %>% 
            # remove date column
            dplyr::select(!Date),
          # modify columns 
          columns = list(Population = colDef(format = colFormat(separators = TRUE)),
                         Cases = colDef(format = colFormat(separators = TRUE)),
                         cases_per_pop = colDef(name = "Percent of Cases", 
                                                format = colFormat(percent = TRUE,
                                                                   digits = 2)),
                         Deaths = colDef(format = colFormat(separators = TRUE)),
                         deaths_per_pop = colDef(name = "Percent of Deaths",
                                                 format = colFormat(percent = TRUE,
                                                                    digits = 2)),
                         full_vacc = colDef(name = "Fully Vaccinated",
                                            format = colFormat(separators = TRUE)),
                         full_vacc_per_pop = colDef(name = "Percent Fully Vaccinated",
                                                    format = colFormat(percent = TRUE,
                                                                       digits = 2)),
                         partial_vacc = colDef(name = "Partially Vaccinated",
                                               format = colFormat(separators = TRUE)),
                         partial_vacc_per_pop = colDef(name = "Percent Partially Vaccinated",
                                                       format = colFormat(percent = TRUE, digits = 2))),
                     defaultSorted = list(Cases = "desc"),
                     bordered = TRUE,
                     highlight = TRUE,
                     showPageSizeOptions = TRUE,
                     pageSizeOptions = c(5, 10, 20, 50),
                     defaultPageSize = 5)
```

# OR FIGS.

## Tables

```{r, echo=FALSE}
reactable::reactable(or_current %>% 
            # remove date column
            dplyr::select(!Date),
          # modify columns 
          columns = list(Population = colDef(format = colFormat(separators = TRUE)),
                         Cases = colDef(format = colFormat(separators = TRUE)),
                         cases_per_pop = colDef(name = "Percent of Cases", 
                                                format = colFormat(percent = TRUE,
                                                                   digits = 2)),
                         Deaths = colDef(format = colFormat(separators = TRUE)),
                         deaths_per_pop = colDef(name = "Percent of Deaths",
                                                 format = colFormat(percent = TRUE,
                                                                    digits = 2))),
                     defaultSorted = list(Cases = "desc"),
                     bordered = TRUE,
                     highlight = TRUE,
                     showPageSizeOptions = TRUE,
                     pageSizeOptions = c(5, 10, 20, 50),
                     defaultPageSize = 5)
```


```{r}
cases_tb <- or_current %>%
  select(County, Population, Cases, cases_per_pop) %>% 
  arrange(desc(cases_per_pop)) %>%
  head(5) %>%
  gt::gt()
cases_tb
```
