---
title: "test_data"
author: "Randi Bolt"
date: "6/6/2022"
output: html_document
---

```{r setup, include=FALSE}
here::i_am("05_misc/sandbox/00_data_test.Rmd")
knitr::opts_chunk$set(echo = TRUE)
```

# Data Test

This sandbox file is used to make sure that data files work properly. 

## Raw Data

### NYT Data

```{r NYT data, echo=FALSE}
# location of NYT data 
location_of_NYT_data <- here::here("01_data/raw_data",
                                   "raw_data_NYT.rds")

# NYT data
states_covid <- base::readRDS(location_of_NYT_data)[[1]]
counties_covid <- base::readRDS(location_of_NYT_data)[[2]]
vacc <- base::readRDS(location_of_NYT_data)[[3]]
us_data_date <- base::readRDS(location_of_NYT_data)[[4]]
or_data_date <- base::readRDS(location_of_NYT_data)[[5]]

# head
head(states_covid)
head(counties_covid)
head(vacc)
us_data_date
or_data_date
```

### Census Data

```{r census data, echo=FALSE}
# location of census data
location_of_census_data <- here::here("01_data/raw_data",
                                      "raw_data_census.rds")

# census data
us_pop <- base::readRDS(location_of_census_data)[[1]]
or_pop <- base::readRDS(location_of_census_data)[[2]]

# head 
head(us_pop)
head(or_pop)
```

### Dates Data 

```{r}
# location of data
location_of_dates_data <- here::here("01_data/raw_data",
                                     "raw_data_dates.rds")

# dates data
today <- base::readRDS(location_of_dates_data)[[1]]
us_close <- base::readRDS(location_of_dates_data)[[2]]
or_close <- base::readRDS(location_of_dates_data)[[3]]

# dates
today
us_close
or_close
```

## Clean Data 

### Census
```{r}
# location of data
location_of_clean_census <- here::here("01_data/clean_data",
                                       "clean_data_census.rds")

# clean data
us_pop <- base::readRDS(location_of_clean_census)[[1]]
or_pop <- base::readRDS(location_of_clean_census)[[2]]

# head
head(us_pop)
head(or_pop)
```

### US Covid 

```{r us covid}
# location of data
location_of_us_covid <- here::here("01_data/clean_data",
                                   "clean_data_us_covid.rds")
# save data 
us_clean <- base::readRDS(location_of_us_covid)

# head
head(us_clean)
```

### OR Covid 

```{r or covid}
# location of data
location_of_us_covid <- here::here("01_data/clean_data",
                                   "clean_data_us_covid.rds")
location_of_or_covid <- here::here("01_data/clean_data",
                                   "clean_data_or_covid.rds")
# save data 
us_clean <- base::readRDS(location_of_us_covid)
or_clean <- base::readRDS(location_of_or_covid)

# head
head(us_clean)
head(or_clean)
```

### dates

```{r dates}
# location of data
location_of_dates_data <- here::here("01_data/clean_data",
                                     "clean_data_dates.rds")

# save data
todays_date <- base::readRDS(location_of_dates_data)[[1]]
us_close_date <- base::readRDS(location_of_dates_data)[[2]]
or_close__date <- base::readRDS(location_of_dates_data)[[3]]
us_data_date <- base::readRDS(location_of_dates_data)[[4]]
or_data_date <- base::readRDS(location_of_dates_data)[[5]]
# data
todays_date
us_close_date
or_close_date
us_data_date
or_data_date
```

### current data

```{r current}
# location of data
location_of_current <- here::here("01_data/clean_data",
                                  "clean_data_current.rds")
# save data
us_current <- base::readRDS(location_of_current)[[1]]
or_current <- base::readRDS(location_of_current)[[2]]

# head
head(us_current)
head(or_current)
```

### new data

```{r new data}

```

### or geocode

```{r or geocode}

```
