---
title: "2022 Table Test"
author: "Randi Bolt"
date: "5/12/2022"
output: html_document
---

```{r, include=FALSE}
here::i_am("sandbox/2022_table_test.Rmd")

library(reactable)
library(magrittr)
library(dplyr)
```

```{r load data, include=FALSE, echo=FALSE}
# dates data
date_today <- base::readRDS(here::here("raw_data", "dates_list.rds"))[[1]]
us_data_date <- base::readRDS(here::here("raw_data", "dates_list.rds"))[[4]]
or_data_date <- base::readRDS(here::here("raw_data", "dates_list.rds"))[[5]]
# clean data  
us_clean <- base::readRDS(here::here("clean_data", "clean_data_list.rds"))[[1]]
or_clean <- base::readRDS(here::here("clean_data", "clean_data_list.rds"))[[2]]
# current data 
us_current <- base::readRDS(here::here("clean_data", "clean_data_list.rds"))[[3]]
or_current <- base::readRDS(here::here("clean_data", "clean_data_list.rds"))[[4]]
```


```{r}
us_new <- us_clean %>% 
  select()
```


```{r}
# create new df without Date column
# us_tb_01 <-us_current %>% select(!Date)
# Add commas to: 
# us_tb_01$Population <-base::prettyNum(us_tb_01$Population, big.mark = ",")
# us_tb_01$Cases <-base::prettyNum(us_tb_01$Cases, big.mark = ",")
# us_tb_01$Deaths <-base::prettyNum(us_tb_01$Deaths, big.mark = ",")
# us_tb_01$full_vacc <-base::prettyNum(us_tb_01$full_vacc, big.mark = ",")
# us_tb_01$partial_vacc <-base::prettyNum(us_tb_01$partial_vacc, big.mark = ",")
# # add % to 
# us_tb_01$cases_per_pop <- base::sprintf("%0.2f%%", us_tb_01$cases_per_pop*100)
# us_tb_01$deaths_per_pop <- base::sprintf("%0.2f%%", us_tb_01$deaths_per_pop*100)

# head(us_tb_01)
```

```{r us current reactable}
reactable(us_current %>% 
            # remove date column
            dplyr::select(!Date),
          # modify columns 
          columns = list(Population = colDef(format = colFormat(separators = TRUE)),
                         Cases = colDef(format = colFormat(separators = TRUE)),
                         cases_per_pop = colDef(name = "Percent of Cases", 
                                                format = colFormat(percent = TRUE,
                                                                   digits = 2)),
                         Deaths = colDef(format = colFormat(separators = TRUE)),
                         deaths_per_pop = colDef(name = "Percent of Deaths",
                                                 format = colFormat(percent = TRUE,
                                                                    digits = 2)),
                         full_vacc = colDef(name = "Fully Vaccinated",
                                            format = colFormat(separators = TRUE)),
                         full_vacc_per_pop = colDef(name = "Percent Fully Vaccinated",
                                                    format = colFormat(percent = TRUE,
                                                                       digits = 2)),
                         partial_vacc = colDef(name = "Partially Vaccinated",
                                               format = colFormat(separators = TRUE)),
                         partial_vacc_per_pop = colDef(name = "Percent Partially Vaccinated",
                                                       format = colFormat(percent = TRUE, digits = 2))),
                     defaultSorted = list(Cases = "desc"),
                     bordered = TRUE,
                     highlight = TRUE,
                     showPageSizeOptions = TRUE,
                     pageSizeOptions = c(5, 10, 20, 50),
                     defaultPageSize = 5)
```

```{r}
reactable(or_current %>% 
            # remove date column
            dplyr::select(!Date),
          # modify columns 
          columns = list(Population = colDef(format = colFormat(separators = TRUE)),
                         Cases = colDef(format = colFormat(separators = TRUE)),
                         cases_per_pop = colDef(name = "Percent of Cases", 
                                                format = colFormat(percent = TRUE,
                                                                   digits = 2)),
                         Deaths = colDef(format = colFormat(separators = TRUE)),
                         deaths_per_pop = colDef(name = "Percent of Deaths",
                                                 format = colFormat(percent = TRUE,
                                                                    digits = 2))),
                     defaultSorted = list(Cases = "desc"),
                     bordered = TRUE,
                     highlight = TRUE,
                     showPageSizeOptions = TRUE,
                     pageSizeOptions = c(5, 10, 20, 50),
                     defaultPageSize = 5)
or_current
```



```{r}
or_new <- us_clean %>% 
  dplyr::select(Date, State, Cases, Deaths, full_vacc, partial_vacc) %>% 
  dplyr::filter(State == "Oregon") %>%
  dplyr::arrange(Date) %>%
  dplyr::mutate(new_cases = Cases - lag(Cases, default = first(Cases)),
         new_deaths = Deaths - lag(Deaths, default = first(Deaths)),
         new_full_vacc = full_vacc - lag(full_vacc, default = first(full_vacc)),
         new_part_vacc = partial_vacc - lag(partial_vacc, default = first(partial_vacc)))
or_new
```

```{r}
library(magrittr)
library(dplyr)
```


```{r}
mini_us_clean <- head(us_clean, 10)
mini_us_clean
```

```{r}

```



```{r}
us_new <- us_clean %>%
  select(Date, Cases) %>%
  group_by(Date) %>%
  summarise(new_cases = sum(Cases))
us_clean
us_new
```


```{r}
reactable(or_new_cases)
```



```{r}
# new cases oregon
or_new_cases <- us_clean %>%
  select(Date, State, Cases) %>%
  filter(State == "Oregon") %>%
  arrange(Date) %>%
  mutate(New_Cases = Cases - lag(Cases, default = first(Cases)))
barplot(or_new_cases$New_Cases)
```
