---
title: "Bonus Data"
author: "Randi Bolt"
date: "5/16/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(tidycensus)
library(dplyr)
```

## Bonus Data 

Removed from raw data. 

```{r }
# 00_05: BONUS DATA (not used bc/ not updated since 2021)
policytrackerOR_data <- read_csv("https://raw.githubusercontent.com/govex/COVID-19/govex_data/data_tables/policy_data/table_data/Current/Oregon_policy.csv")
college_data <- read_csv('https://raw.githubusercontent.com/nytimes/covid-19-data/master/colleges/colleges.csv')
mask_use_data <- read_csv('https://raw.githubusercontent.com/nytimes/covid-19-data/master/colleges/colleges.csv')


state_den_data <- get_estimates(geography = "state", 
                                year = 2019, 
                                variable =  "DENSITY") 

or_den_data <- get_estimates(geography = "county", 
                             state = "OR", 
                             year = 2019, 
                             variable = "DENSITY")

# location of data (bonus)
location_of_policytracker <- here::here("raw_data",
                                        "policy_tracker_or_data.rds")
location_of_college <- here::here("raw_data",
                                  "college_covid_data.rds")
location_of_mask_use <- here::here("raw_data",
                                   "mask_use_data.rds")
location_of_state_den <- here::here("raw_data",
                                    "state_den_data.rds")
location_of_or_den <- here::here("raw_data",
                                 "or_den_data.rds")

# save data (bonus)
saveRDS(policytrackerOR_data, location_of_policytracker)
saveRDS(college_data, location_of_college)
saveRDS(mask_use_data, location_of_mask_use)
saveRDS(state_den_data, location_of_state_den)
saveRDS(or_den_data, location_of_or_den)
```
